// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swxhiixiggfzaastzovo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3eGhpaXhpZ2dmemFhc3R6b3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTA1OTgsImV4cCI6MjA2OTUyNjU5OH0.Fd2KQt3t8u_d3rE5JqxIIO-bdJNiMI2Zwyz_r5VWRCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});